CREATE TABLE WF_WORKFLOW_APPROVAL_RELATION (
TASK_ID VARCHAR(45) NOT NULL,
EVENT_ID VARCHAR(45) NOT NULL,
WORKFLOW_ID VARCHAR(45) NOT NULL,
APPROVER_TYPE VARCHAR(45) NOT NULL,
APPROVER_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY(TASK_ID),
FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);

CREATE TABLE WF_WORKFLOW_APPROVAL_STATE (
EVENT_ID VARCHAR(45) NOT NULL,
WORKFLOW_ID VARCHAR(45) NOT NULL,
CURRENT_STEP INTEGER,
CONSTRAINT PK_WF_APPROVAL_STATE_CONSTRAINT PRIMARY KEY (EVENT_ID, WORKFLOW_ID),
FOREIGN KEY (EVENT_ID) REFERENCES  WF_REQUEST(UUID) ON DELETE CASCADE,
FOREIGN KEY (WORKFLOW_ID) REFERENCES  WF_WORKFLOW(ID) ON DELETE CASCADE
);


CREATE INDEX IDX_WF_APPROVAL_STATE ON WF_WORKFLOW_APPROVAL_STATE(EVENT_ID,WORKFLOW_ID);

CREATE INDEX IDX_WF_APPROVAL_RELATION ON WF_WORKFLOW_APPROVAL_RELATION(TASK_ID);


